### ISSUE TITLE
docker image does not work with other mqtt servers since latest update anymore

### ISSUE THREAD

**Issue by scarface-4711** [snipsco/snips-platform-documentation#18]
Since the latest update snips docker image does not work with the mosqitto mqtt which is installed on the docker host anymore.
I get error messages like **ERROR:snips_dialogue: Error: Unsupported bus type: 172.17.0.1:1883**

Mosquitto is of course still running on that IP 
```tcp        0      0 172.17.0.1:1883         0.0.0.0:*               LISTEN```

```bash
docker run -t --rm --name snips --log-driver none -v /home/pi/.asoundrc:/root/.asoundrc -v /opt/snips/config/assistant:/usr/share/snips/assistant --privileged -v /dev/snd:/dev/snd snipsdocker/platform --mqtt 172.17.0.1:1883
sed: can't read /root/resources/snips.ini: No such file or directory
sed: can't read /root/resources/snips.ini: No such file or directory
snips-asr-google is disabled
Spawning /usr/bin/snips-asr --no_fst_map --beam_size=8 --bus '172.17.0.1:1883'
Spawning /usr/bin/snips-audio-server --bus '172.17.0.1:1883' --frame=256
Spawning /usr/bin/snips-tts --bus '172.17.0.1:1883'
Spawning /usr/bin/snips-hotword --bus '172.17.0.1:1883'
Spawning /usr/bin/snips-queries --bus '172.17.0.1:1883'
Spawning /usr/bin/snips-dialogue --bus '172.17.0.1:1883'
snips-analytics is disabled
snips-debug is disabled
2017-11-20 00:02:27,545 CRIT Supervisor running as root (no user in config file)
2017-11-20 00:02:27,553 INFO supervisord started with pid 38
2017-11-20 00:02:28,559 INFO spawned: 'snips-tts' with pid 41
2017-11-20 00:02:28,568 INFO spawned: 'snips-dialogue' with pid 42
2017-11-20 00:02:28,576 INFO spawned: 'snips-asr' with pid 43
2017-11-20 00:02:28,583 INFO spawned: 'snips-hotword' with pid 44
2017-11-20 00:02:28,592 INFO spawned: 'snips-audio-server' with pid 45
2017-11-20 00:02:28,600 INFO spawned: 'snips-queries' with pid 46
ERROR:snips_dialogue: Error: Unsupported bus type: 172.17.0.1:1883

ERROR:snips_tts: Error: Unsupported bus type: 172.17.0.1:1883

2017-11-20 00:02:28,643 INFO exited: snips-tts (exit status 1; not expected)
2017-11-20 00:02:28,647 INFO exited: snips-dialogue (exit status 1; not expected)
Error: Unsupported bus type: 172.17.0.1:1883

```

**Comment by Romkabouter** [comment]
same here

**Comment by cruxlin** [comment]
There is a mistake in /opt/snips/snips-entrypoint.sh, In line 271,
SNIPS_MQTT_FLAG="--bus '$SNIPS_MQTTHOST:$SNIPS_MQTT_PORT" => it's wrong so cause "Error: Unsupported bus type: 172.17.0.1:1883"
Correct one is 
SNIPS_MQTT_FLAG="--**mqtt** '$SNIPS_MQTTHOST:$SNIPS_MQTT_PORT"

**Comment by scarface-4711** [comment]
@cruxlin: thanks your fix is working for me

**Comment by Romkabouter** [comment]
Hi there, how can I fix this?

**Comment by cysieks** [comment]
Could you please fix docker image?

**Comment by thundergreen** [comment]
Same issue here ..his would i change this manually?

**Comment by tschmidty69** [comment]
This is fixed with the latest update along with a few other nice features (can add a /share/snips.toml to customize tts for example)

**Comment by Romkabouter** [comment]
I do not think it is fixed, I see the same line:
SNIPS_MQTT_FLAG="--bus '$SNIPS_MQTTHOST:$SNIPS_MQTT_PORT'"
still in docker latest (0.6.5.)

**Comment by tschmidty69** [comment]
Docker latest should pull 0.51.14. Oh, I see they still have an old 'latest' tag. The new ones you need to use arm-latest and x86-latest. Would also be annoying if trying to use the x86 since latest tags an arm version.

**Comment by Romkabouter** [comment]
Well, that explains! Thnx
